### ISSUE TITLE
Программа почему-то посчитала предлог

### ISSUE THREAD

**Issue by gururuby** [rawenfalls/count_words#11]
![image](https://user-images.githubusercontent.com/853829/34587487-9481105e-f1b9-11e7-88ae-7ee88484015a.png)

**Comment by rawenfalls** [comment]
исправленно

**Comment by gururuby** [comment]
![image](https://user-images.githubusercontent.com/853829/34601639-f88e01ca-f20d-11e7-8492-57f5542a2dd3.png)
Не работает

**Comment by rawenfalls** [comment]
исправил

**Comment by gururuby** [comment]
![image](https://user-images.githubusercontent.com/853829/34608461-7866d65e-f229-11e7-8cec-9d58d34d3662.png)
и союз "и" еще посчитала

**Comment by rawenfalls** [comment]
![_2018-01-05_21-33-45](https://user-images.githubusercontent.com/33192916/34622926-2ad000d2-f260-11e7-8f3a-da829d02c7c0.png)
