### ISSUE TITLE
переписать на более простой код

### ISSUE THREAD

**Issue by gururuby** [rawenfalls/count_words#6]
https://github.com/rawenfalls/count_words/blob/2b5b060771e2f34c95c9f8b0cf33ba9ea48ea15e/count_words.rb#L7

Для открытия существующего файла в руби есть определенный метод, у класса File он так и называется. Скрипт ты запускаешь из текущей директории поэтому не обязательно мучаться с этими current_file и прочее, должно работать просто так - File.open('file_name')

**Comment by rawenfalls** [comment]
готово
