### ISSUE TITLE
Необходимо чтобы программа воспринимала слова со спецсимволами

### ISSUE THREAD

**Issue by gururuby** [rawenfalls/count_words#8]
Пример: Сатурн5 определенное_слово, человек-паук

**Comment by rawenfalls** [comment]
готово

**Comment by gururuby** [comment]
![image](https://user-images.githubusercontent.com/853829/34580252-62d6973e-f19d-11e7-9b00-44f0e604f5df.png)
Некорректно работает

**Comment by gururuby** [comment]
Необходимо чтобы слова с _ - и цифрами программа воспринимала как слова
